---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  # Redis server hostname and port (e.g. argocd-redis:6379 HA: argocd-redis-ha:6379)
  redis.server: "argocd-redis:6379"
  applicationsetcontroller.enable.leader.election: "true"

#https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml