apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |

    g, "api_user", role:org-admin

    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, applicationsets, *, */*, allow
    p, role:org-admin, clusters, *, *, allow
    p, role:org-admin, projects, *, *, allow
    p, role:org-admin, repositories, *, *, allow
    p, role:org-admin, certificates, *, *, allow
    p, role:org-admin, logs, *, *, allow
    p, role:org-admin, accounts, *, *, allow
    p, role:org-admin, gpgkeys, *, *, allow
    p, role:org-admin, exec, create, *, allow