---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server  
spec:
  template:
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: argocd-server
          args: [/usr/local/bin/argocd-server, --staticassets, /shared/app, --insecure, --enable-gzip]
