apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  #  accounts.api_user: apiKey
  application.resourceTrackingMethod: label
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  repository.credentials: |
    - url: git@github.com:daryaolejnik
      sshPrivateKeySecret:
        name: argocd-repo-key
        key: sshPrivateKey
  repositories: |
    - url: git@github.com:daryaolejnik/argocd.git
    - type: helm
      name: stable
      url: https://charts.helm.sh/stable

#  url: https://PLACEHOLDER.pp.ua
