---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  description: ArgoCD project
  sourceRepos:
    - '*'
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd
  annotations:

spec:
  destination:
    namespace: argocd
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  project: argocd
  source:
    repoURL: git@github.com:daryaolejnik/argocd.git
    targetRevision: HEAD
    path: argocd
