---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: argocd
  name: argocd-ingress
  labels:
    app.kubernetes.io/name: argocd-ingress
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-north-1:102205351130:certificate/26d4a81f-0696-4994-8363-8d2be24799db
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    # certificate annotations
spec:
  #   tls:
  #     - hosts:
  #         - argocd.doliinyk-app.pp.ua
  rules:
    - host: argocd.doliinyk-app.pp.ua
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http
