apiVersion: v2
name: metrics-server-infrastructure
description: Metrics Server for the cluster infrastructure
type: application
version: 0.1.0

dependencies:
  - name: metrics-server
    version: "3.13.0"
    repository: "https://kubernetes-sigs.github.io/metrics-server/"
