apiVersion: v2
name: ingress-nginx-infrastructure
description: NGINX Ingress Controller for the cluster infrastructure
type: application
version: 0.1.0
appVersion: "1.9.4"

dependencies:
  - name: ingress-nginx
    version: "4.7.1"
    repository: "https://kubernetes.github.io/ingress-nginx"
